name: CI

on:
  push:
    branches:
      - main # Запуск при пуше в ветку main
  pull_request:
    branches:
      - main # Запуск при создании PR в ветку main
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка кода из репозитория
        uses: actions/checkout@v2

      - name: Set up Python # Шаг для настройки Python окружения
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies # Шаг для установки зависимостей проекта
        run: |
          pip install bandit 

      - name: Check security # Шаг для проверки безопасности кода
        run: bandit app/rgr.py .
